# Generated by Django 5.1.1 on 2026-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('fundacional', 'Fase Fundacional'), ('intermedia', 'Fase Intermedia'), ('avanzada', 'Fase Avanzada'), ('transversal', 'Transversal'), ('asignatura', 'Por Asignatura')], max_length=20)),
                ('icon_image', models.ImageField(blank=True, upload_to='assistants/icons/')),
                ('openai_assistant_id', models.CharField(blank=True, help_text='ID del asistente en OpenAI (asst_xxx).', max_length=100)),
                ('available_courses', models.JSONField(default=list, help_text='Lista de cursos que pueden acceder: [1,2,3]')),
                ('allows_custom_cases', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(blank=True, help_text='Instrucciones del sistema para el asistente.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
