# Generated by Django 5.1.1 on 2026-03-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Puntuación general 1-10')),
                ('strengths', models.TextField(help_text='Puntos fuertes del estudiante')),
                ('improvements', models.TextField(help_text='Áreas de mejora')),
                ('summary', models.TextField(help_text='Resumen general de la evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.chatsession')),
            ],
        ),
    ]
