# Generated by Django 5.1.1 on 2026-05-04 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('gradient_from', models.CharField(default='#003973', max_length=8)),
                ('gradient_to', models.CharField(default='#00509e', max_length=8)),
                ('deco_code', models.CharField(blank=True, max_length=8)),
                ('group', models.CharField(choices=[('cardio', 'Cardiorrespiratorios'), ('digestive', 'Digestivos y urinarios'), ('neuro', 'Sistema nervioso'), ('general', 'Síntomas generales')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx', models.CharField(max_length=200)),
                ('compat', models.CharField(choices=[('neutral', 'Neutral'), ('positive', 'Positive'), ('strong', 'Strong')], max_length=10)),
                ('symptoms', models.JSONField(default=list)),
                ('key_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_combos', to='anamnesis.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('diagnosis_key', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='anamnesis.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='anamnesis.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='anamnesis.quizquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('example_question', models.TextField(blank=True)),
                ('think_box', models.TextField(blank=True)),
                ('tip_box', models.TextField(blank=True)),
                ('sec_label', models.CharField(blank=True, max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='anamnesis.module')),
            ],
            options={
                'ordering': ['module', 'n'],
                'unique_together': {('module', 'n')},
            },
        ),
        migrations.CreateModel(
            name='IrrelevantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('body_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrelevant_items', to='anamnesis.step')),
            ],
            options={
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FlipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('back_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flip_cards', to='anamnesis.step')),
            ],
            options={
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepDxFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_idx', models.PositiveSmallIntegerField()),
                ('compat', models.CharField(choices=[('neutral', 'Neutral'), ('positive', 'Positive'), ('strong', 'Strong')], max_length=10)),
                ('evidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('interpretation', models.TextField()),
                ('fits_for', models.JSONField(default=list)),
                ('rules_out', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_feedbacks', to='anamnesis.patient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_feedbacks', to='anamnesis.step')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('persona_summary', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_patients', to='assistants.assistant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_patients', to='anamnesis.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PatientQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='anamnesis.patient')),
            ],
            options={
                'ordering': ['patient', 'step_number'],
                'unique_together': {('patient', 'step_number')},
            },
        ),
    ]
