# Generated by Django 5.1.1 on 2026-05-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_quizattempt_studentevent_moduleprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stepdxfeedback',
            unique_together={('step', 'patient', 'quote_idx')},
        ),
    ]
