# Generated by Django 5.1.1 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0003_alter_stepdxfeedback_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
