# Generated by Django 5.1.1 on 2026-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0004_alter_quizattempt_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualpatient',
            name='card_blurb',
            field=models.CharField(blank=True, help_text='Public-facing short description shown on the patient card. Must NOT mention the diagnosis — that is for the LLM persona only.', max_length=300),
        ),
    ]
