# Generated by Django 5.1.1 on 2026-05-04 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0005_virtualpatient_card_blurb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'module'], name='anamnesis_q_student_dfc2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['module'], name='anamnesis_q_module__8104e5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentevent',
            index=models.Index(fields=['module', 'event_type'], name='anamnesis_s_module__2ade49_idx'),
        ),
        migrations.AddIndex(
            model_name='studentevent',
            index=models.Index(fields=['student', 'module'], name='anamnesis_s_student_eb3bdd_idx'),
        ),
    ]
